using OnlineShoppingStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class NavController : Controller
    {   //if there is a NavController, then there is a Nav View folder, this one contains one cshtml partial page called Menu.cshtml
        //Menu holds the Home button, and buttons of different categories generated by the Menu method residing here

        private IProductRepository repository;    //IProductRepository has a single property, contains collection of Products

        public NavController(IProductRepository repo)         //this is called dependency injection
        {
            repository = repo;  //repository shall have Products and the properties of Product
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;          

            IEnumerable<string> categories = repository.Products    //query all unique Category value in IProductRepository and make it a categories collection
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);  //category names
        }
    }
}